verbose: true
verbose player only: true
get command activated: true
disarm mainhand: true
must be op to use: true
rules:
  - Play nice
  - Respect other people's privacy and claims after they trusted you

chat-style: BOLD
chat-color: RED
name-style: ITALIC
name-color: BLUE

format-string: blablalba

clockLore: Time Transfer Device (very ancient)