verbose: true
verbose-player-only: true
get-command: true
disarm-mainhand: true
cc-must-be-op: true
relay-chests: false

rules:
  - Respect other people's privacy and claims after they trusted you

chat-style: BOLD
chat-color: RED
name-style: ITALIC
name-color: BLUE

format-string: blablalba

