# File: src/main/resources/config.yml

verbose: true
verbose-player-only: true
get-command: true
replace-emoji: true
disarm-mainhand: true
cc-must-be-op: true
relay-chests: false
literally-1984: false

rules:
  - Respect other people's privacy and claims after they trusted you

chat-style: BOLD
chat-color: RED
name-style: ITALIC
name-color: BLUE

format-string: TODO!